"""del group_id

Revision ID: 7efeb3b9f4d9
Revises: 7c171827b74f
Create Date: 2023-07-03 01:34:47.491324

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '7efeb3b9f4d9'
down_revision = '7c171827b74f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lesson_group_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('lesson_group_id_fkey', 'event', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###
