"""add EventUser table

Revision ID: 8006ac22acc4
Revises: 55a049fde8f4
Create Date: 2026-04-20 16:21:11.459713

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8006ac22acc4'
down_revision = '55a049fde8f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'event_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column(
            'status',
            sa.Enum('NO_STATUS', 'GOING', 'NOT_GOING', 'ATTENDED', name='eventuserstatus', native_enum=False),
            nullable=False,
        ),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ['event_id'],
            ['event.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.drop_constraint(op.f('lesson_group_id_fkey'), 'event', type_='foreignkey')
    op.drop_column('event', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('lesson_group_id_fkey'), 'event', 'group', ['group_id'], ['id'])
    op.drop_table('event_user')
    # ### end Alembic commands ###
